# Definition of nodes
peer1: &peer1
  addr: localhost:30000
  user-agent: /peer1-example.com
  tls_ca_cert: ./nginx.pem

peer2: &peer2
  addr: localhost:30000
  user-agent: /peer2-example.com
  tls_ca_cert: ./nginx.pem

orderer1: &orderer1
  addr: localhost:30000
  user-agent: /orderer1.bc69jkmh6onw
  tls_ca_cert: ./nginx.pem

# Nodes to interact with
endorsers:
  - *peer1
  - *peer2
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committer: *peer2
orderer: *orderer1

# Invocation configs
channel: performance
chaincode: fabcar
args:
  - queryAllCars
mspid: Org1MSP
private_key: ./priv_sk
sign_cert: ./cert.pem
num_of_conn: 10
client_per_conn: 10
